### ISSUE TITLE
error opening app - in Debian system

### ISSUE THREAD

**Issue by ELQET** [Storj/driveshare-gui#31] opened 2015-09-29 19:12 UTC
Please check this screenshot of error I have got when "npm start". I have done all step by step by guide in github page for GUI for driveshare app.
![driveshare_gui_error](https://cloud.githubusercontent.com/assets/6269862/10175341/8f4d314c-66ee-11e5-8883-18a40cb801c7.png)

**Comment by gamedevsam** [comment] 2015-09-30 18:14
Thanks for your report, is this from a fresh install or an upgrade? Did you try running npm install before npm start?

**Comment by ELQET** [comment] 2015-09-30 18:44
First I had installed dataserv-client and there is no problem with that. I have the latest greatest version. And after that after some time I decided to try GUI so I installed it from GitHub repository and did all the steps.  But it haven't work so I decided to install nodejs and npm with apt-get install. Because I am familiar with nodejs and I noticed that you are using it so I decided to install it. After that I once again have tried to do this steps to run GUI from GitHub repository. Without luck. The same problem. Has it something to do with my ITX Intel Atom based system? Or something else?

**Comment by ELQET** [comment] 2015-09-30 18:46
if you mean fresh install of linux distro yes it is. To be specific it is debian based xubuntu.

**Comment by ELQET** [comment] 2015-09-30 18:47
yes I have tried npm install you can see it on screenshot :)

**Comment by gamedevsam** [comment] 2015-09-30 19:44
Could you try installing the missing module to see if it fixes it?
```npm install accord```

**Comment by gamedevsam** [comment] 2015-09-30 19:46
Additionally, you could try deleting the ```node_modules``` and ```app/node_modules``` folder and try running ```npm install``` again from the dataserv-gui directory.

**Comment by gamedevsam** [comment] 2015-10-26 03:00
I'm closing this issue for now since I cannot reproduce it in my Ubuntu VirtualBox image.

**Closed by gamedevsam** 2015-10-26 03:00 UTC
