### ISSUE TITLE
Install issues

### ISSUE THREAD

**Issue by ubronan** [Storj/driveshare-gui#98] opened 2015-12-11 00:33 UTC
When i took the time to investigate the new release i ran instant into a few issues.
Although the first plain install looked like it ran fine, i pressed the close button and got an empty page.
second install gave the program admin rights and tried again no luck either.
Suddenly remembered that i had run driveshare several times from pre-aplha day one.
So i deleted everything i could find from the old installs and turned out alot of residu was on the drive left.
Then i started again the installer as user and tried ..... again failed
Set the program as win 8 and started the installer as admin this time i got further it actually showed a download screen which hang for 8 minutes on 4 Mb and since that is too long for any value to be downloaded on my 80 Mbit line.
I killed the program and tried several times with rights being given to the programs as the user.
Sadly it failed each time to download the needed client files.
I decided to actually give driveshare.exe admin rights in the install folder and full trusted user rights.
Now the program instant downloaded the full remaining files and started as it should.
Because i did not had much storage on the machine from start i had moved the files over to the synology nas so i could experiment with the program.
So i think some rights issues make the program fail, Again i installed the program as admin with all rights to the installer. When it started the driveshare it seems to fail on the same rights issue.
Ofcourse do note i am running a win 10 x64 edition and not the 32bit one.
This normally should not matter however it could be related to the issues.
So i made a network mapping direct to the moved files example o:\data and started the program. 
Several errors where given because its linux synology storage. but seems to build a few renewed shards and after started to constant message : INFO 46: finding neighbors of 121815135605534387749688133360806705560617585289 in local table and so on long list of numbers passing by, is this the checking of the shards or should i delete all of them and start over?.
Because i added a second drive with 1.8 Tb i added this drive as g:\data and am letting it build another Tb data on it. If this all succeeds i might pump it up to 10 Tb if we finally get info on reward and build limits
So seems some work still to be done because the program get insuffients rigths on windows 10 and probably also on earlier versions. This might also cause the failure of the check free space tool.
Because not enough rights is bound to fail, win 10 is a bad boy regarding access to hardware if not enough rights todo so. Looks like my test with win 8 and 8.1 vmware images shows similar problems with installing. Also all of the used images are x64 ones. We do not use x32 anymore at work. 
One last tip when users download the program it gets tagged blocked by windows, user should check with rightclicking on the installer to unlock the program for allow it to be installed. When they do so they can instant start the installer as admin. But ofcourse the rights in the program files folder has to be correct to allow the program to access the disks

**Comment by littleskunk** [comment] 2015-12-11 22:31
This is more than one issue. Lets do this step by step.

1.) The 32bit binary will work for 64bit windows as well. We don't need the profit of a 64bit application.

2.) "INFO 46: finding neighbors of 121815135605534387749688133360806705560617585289 in local table and so on long list of numbers passing by, is this the checking of the shards or should i delete all of them and start over?"

We implemented a p2p node into dataserv-client. You can see the p2p log. At the moment the p2p stuff is running in the background. We will add file transfer later. At the moment you can ignore the messages.

3.) "This might also cause the failure of the check free space tool."
We are working on that issue: https://github.com/Storj/driveshare-gui/issues/83

4.) "I killed the program and tried several times with rights being given to the programs as the user.
Sadly it failed each time to download the needed client files."

I had problems yesterday myself but can't reproduce it now. Maybe i can reproduce it with the next driveshare-gui release. Anyway if your download stops you dont need to kill the programm. View->Reload will start the download again.

5.) "One last tip when users download the program it gets tagged blocked by windows, user should check with rightclicking on the installer to unlock the program for allow it to be installed."

We are working on that issue as well: https://github.com/Storj/driveshare-gui/issues/36

5.) "Although the first plain install looked like it ran fine, i pressed the close button and got an empty page. [...] Suddenly remembered that i had run driveshare several times from pre-aplha day one."

The old config file was the problem. I did some migration tests with the 0.3.4 config. I didn't try older versions.

I don't think admin permissions are needed. The installation works with normal user permission. Maybe your system has unusual permission or firewall settings? Did you installed it yourself or did somebody else installed it for you?
You can remove write permission for %appdata% but that is nothing we can fix in the gui.

I will close this now. Thank you for the long description. We are working on the 2 issues and fix them.

**Closed by littleskunk** 2015-12-11 22:31 UTC
Labels: bug, in progress

**Comment by ubronan** [comment] 2015-12-11 23:27
Op 11-12-2015 om 23:31 schreef littleskunk:
>
> This is more than one issue. Lets do this step by step.
>
> 1.) The 32bit binary will work for 64bit windows as well. We don't 
> need the profit of a 64bit application.
>
> 2.) "INFO 46: finding neighbors of 
> 121815135605534387749688133360806705560617585289 in local table and so 
> on long list of numbers passing by, is this the checking of the shards 
> or should i delete all of them and start over?"
>
> We implemented a p2p node into dataserv-client. You can see the p2p 
> log. At the moment the p2p stuff is running in the background. We will 
> add file transfer later. At the moment you can ignore the messages.
>
> 3.) "This might also cause the failure of the check free space tool."
> We are working on that issue: #83 
> <https://github.com/Storj/driveshare-gui/issues/83>
>
> 4.) "I killed the program and tried several times with rights being 
> given to the programs as the user.
> Sadly it failed each time to download the needed client files."
>
> I had problems yesterday myself but can't reproduce it now. Maybe i 
> can reproduce it with the next driveshare-gui release. Anyway if your 
> download stops you dont need to kill the programm. View->Reload will 
> start the download again.
>
> 5.) "One last tip when users download the program it gets tagged 
> blocked by windows, user should check with rightclicking on the 
> installer to unlock the program for allow it to be installed."
>
> We are working on that issue as well: #36 
> <https://github.com/Storj/driveshare-gui/issues/36>
>
> 5.) "Although the first plain install looked like it ran fine, i 
> pressed the close button and got an empty page. [...] Suddenly 
> remembered that i had run driveshare several times from pre-aplha day 
> one."
>
> The old config file was the problem. I did some migration tests with 
> the 0.3.4 config. I didn't try older versions.
>
> I don't think admin permissions are needed. The installation works 
> with normal user permission. Maybe your system has unusual permission 
> or firewall settings? Did you installed it yourself or did somebody 
> else installed it for you?
> You can remove write permission for %appdata% but that is nothing we 
> can fix in the gui.
>
> I will close this now. Thank you for the long description. We are 
> working on the 2 issues and fix them.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Storj/driveshare-gui/issues/98#issuecomment-164066988>.
>
Hi littleskunk,

Yes i agree i think most issues where from the constant updating to 
newer versions and the left over residu.
I forgot to ask if what has been meant with the multi disk build, i 
probably had the wrong idea how it should work.
Tried to run 3 drives on one address but it looks like its not meant to 
work that way
I see 3 builds with the same payout address and in all 3 folders are the 
same shards
Forgot if multidisk build on 1 address was being implemented or not.

I do install everything myself and usually know what i am doing, but 
because i am coming of age, i start to forget things as all older people 
do ;).
However i think some issues also seem to be related to the upgrade from 
win 8.1 to win 10
Found some programs no longer work because the rights somehow seems to 
be lost the owners.
This might also explain why it would not simply over write the old 
files, unless i started it as admin and give it full access.
Anyway i agree that the old config files might had caused most problems 
anyway.

I also have been trying several times to get storj running on my 
synology 2414+ nas, but it fails to get installed beyond v1.3.0
It simply refuses to update to the newer versions, i tried with python 2 
and later with 3 but each time it ends at the same point no upgrading

regards,

bronan

**Comment by littleskunk** [comment] 2015-12-12 00:07
For synology this was postet some days ago: https://docs.google.com/document/d/1EqcCdJARBR1mvghgXR5ZcXQauoZEX7Me4YzFUjIwkc4/mobilebasic

slack user reddd did this and maybe he can help you.
