### ISSUE TITLE
Minor Behavior Changes 

### ISSUE THREAD

**Issue by super3** [Storj/driveshare-gui#159] opened 2016-01-06 18:41 UTC
- [x] Change 'Minimize to Tray' to 'Display in Tray'
- [x] If selected, then always display in tray on all platforms
- [x] If you hit the 'X' close button the app will hide
- [x] Left click bring app into context
- [x] Right click context menu

**Comment by littleskunk** [comment] 2016-01-06 21:28
@super3 
Tray icon menu on windows has this order:
>Restore
Quit
Drives + Submenu
>

Quit should stay at last position. Better order would be
>Restore
Drive + Submenu
Quit
>

**Comment by MrFancyMonocle** [comment] 2016-01-06 21:56
Agreed on the menu re-ordering. FYI: there is no right-click distinction on our Linux targets for system tray icons, so left and right will both bring up the context menu here, but we can add a focus option for left-click on OSX and Win still.

**Comment by MrFancyMonocle** [comment] 2016-01-08 20:35
Pull #163

**Comment by darkbluelight** [comment] 2016-01-09 17:28
I'm running DriveShare 0.5.0 on Debian 8 testing (aka stretch) with Kernel 4.3.0-1amd64 x86_64 and with MATE desktop 1.10.2.
Right click on the tray symbol shows me the Restore, Quit, Drives. Left-click on the tray symbol does nothing. Clicking on drives and then on Running: ... crashes the DriveShare GUI. The symbol disappears but DriveShare processes remain running in the background.
(btw awesone job you are doing with storj !)

**Comment by littleskunk** [comment] 2016-01-11 01:44
I have to write down a litte review checklist. I don't want to miss something. I am using the autobin binaries for the develop branch.

Ubuntu (gnome)
Display in System Tray
No duplicate instance allowed.
New tray menu order.
X hide the gui.
X close the gui if tray icon option not set.
Right click show menu.
Left click not working.

Windows
Display in System Tray
No duplicate instance allowed.
New tray menu order.
X hide the gui.
X close the gui if tray icon option not set.
Left click restore gui.
Right click show menu.

OSX
Display in System Tray
No duplicate instance allowed.
X always hide the gui without tray icon. (expected behavior as far as i know)
Left click restore gui.
Right click show menu with only one default entry "open".

Not working:
Windows tray icon is hidden in a drop down menu. Start the gui a second time is not working. It looks like the gui is broken. I can hit the desktop icon or task bar icon but nothing happens. The gui is still running in the background. Can you bringt it to the front? Same problem on ubuntu and osx but there the tray icon is not hidden in a drop down menu.

ubuntu left click doesn't bring the gui in front. Right-click->restore is not far away and works. Is it the expected behavior for linux?

No tray icon menu for osx. Other programms have menus for there task bar icons. Where is the menu expected for osx?

**Comment by MrFancyMonocle** [comment] 2016-01-11 19:34
Yes, the Windows tray icon in the drop-down is simply how Windows handles these icons and can be changed in OS settings, but not by the app. We're purposefully preventing the GUI from displaying in two instances, so this is a feature we want. I'm testing on a Win 7 vm and seeing the system tray icon restore on left-click, open the context menu on right-click, and get focus when a new instance is attempting to open, without starting a new process.

@littleskunk you're testing the code in pull #163?

**Comment by littleskunk** [comment] 2016-01-11 20:17
I am using the autobin binaries. https://github.com/Storj/driveshare-gui/releases/tag/untagged-71f6a1d7f06c5a4ae16f
The release is 5 days old but i deleted the binaries yesterday to get new binaries for the current develop branch (including pull #163)

Please take a look on the task bar icon. As long as the gui is only minimized I get this icon.
![minimized](https://cloud.githubusercontent.com/assets/6333390/12245387/7b59d4d6-b8a8-11e5-995a-775fd6257f9d.jpg)
It has a litte blue line at the bottom. Start a new process will restore the minimized process. Everything works as expected.

I have problems with the gui if i close it with X. I still have the tray icon but the task bar icon looks different because this time the gui is not only minimized.
![closed](https://cloud.githubusercontent.com/assets/6333390/12245319/25fc46cc-b8a8-11e5-9357-ae0af28f6adb.jpg)
Starting a new process is not working for that spezial situation.

**Comment by MrFancyMonocle** [comment] 2016-01-11 20:48
I understand what you mean now; confusing to cover and speak about all these cases. So, if a user closes the application with the window manager's "X" button, while the system tray icon is enabled, and the system tray icon is the only part of the app showing, opening a new instance of the app will not restore the currently running app (it will not start a new one either), and we want it to restore the current app. This is a simple fix. Committing now.

**Comment by MrFancyMonocle** [comment] 2016-01-11 21:01
Pull #166 for dev branch there to open and focus apps that only exist in sys tray if a second app instance is launched. Testing mac context menu again now. Wait to merge.

**Comment by MrFancyMonocle** [comment] 2016-01-11 21:30
Tested Mac. The released .dmg contains the issue; if the current dev codebase is built with npm run release, the mac left-right click issues don't exist. I think maybe the mac binaries were generated prior to the final menu changes.

**Comment by littleskunk** [comment] 2016-01-11 21:33
autobin is not working on osx and linux at the moment. Working on a fix.

**Comment by littleskunk** [comment] 2016-01-12 00:05
Windows is working now. I see no difference on osx and linux. https://github.com/Storj/driveshare-gui/releases/tag/untagged-4f8af1d97152a3202eff

**Comment by super3** [comment] 2016-01-13 15:45
@MrFancyMonocle @littleskunk  Is this issue complete?

**Comment by littleskunk** [comment] 2016-01-14 13:53
Open questions:
ubuntu left click doesn't bring the gui in front. Right-click->restore is not far away and works. Is it the expected behavior for linux?

No tray icon menu for osx. Other programms have menus for there task bar icons. Where is the menu expected for osx?

**Comment by MrFancyMonocle** [comment] 2016-01-14 15:22
This is the expected behavior for Linux; there's a comment above about it. For Mac, a right-click option displays the menu, which would be a ctrl-click on a one-button mouse or a simple right-click on a two-button mouse with that Mac OS setting enabled.

**Comment by littleskunk** [comment] 2016-01-14 19:43
I did a new test and this time i did not use the autobin binaries.

```
git clone https://github.com/Storj/driveshare-gui -b develop
cd driveshare-gui
npm install
npm start
```

This is the menu on the system tray icon 
![screen shot 2015-12-31 at 20 50 28](https://cloud.githubusercontent.com/assets/6333390/12335079/327ad66e-bab2-11e5-89bc-a831c441d8de.png)

This is the menu on the task bar icon
![screen shot 2015-12-31 at 20 58 21](https://cloud.githubusercontent.com/assets/6333390/12335188/bc8bac98-bab2-11e5-9fad-7c06ebb9fbe4.png)

This is the menu from windows.

**Comment by gordonwritescode** [comment] 2016-03-11 19:41
What's the status of this ticket?

**Comment by MrFancyMonocle** [comment] 2016-03-14 14:31
I'm not aware of any outstanding issues here; let's close out, and we'll open a new, specific issue if there's something to work on.

**Closed by MrFancyMonocle** 2016-03-14 14:31 UTC
Labels: enhancement, needs review
