### ISSUE TITLE
Windows 10

### ISSUE THREAD

**Issue by wizardofwhere** [Storj/driveshare-gui#129] opened 2015-12-23 00:56 UTC
I installed the GUI on a computer running windows 10 and received a message that the program will not run on this system.  Is there a fix coming?

**Comment by gordonwritescode** [comment] 2015-12-23 02:45
Yep! See #36

**Comment by super3** [comment] 2015-12-23 15:17
@wizardofwhere Duplicate of #36. Closing.

**Closed by super3** 2015-12-23 15:17 UTC
